name: Code review

on:
  pull_request:


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:com
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Review code
        uses: mohswell/mintify@v1.0.1
        with:
          base_app_url: ${{secrets.BASE_APP_URL}}
          api_key: ${{secrets.API_TOKEN}}